# Generated by Django 5.2.7 on 2025-10-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='LearningJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
